spring.application.name=TransactionService
server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/transaction_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
eureka.instance.instance-id=TransactionService:8083

jwt.secret=MySecretKeyForJwtAuthenticationProject2026SpringBootSecureKey123456789