spring.application.name=api-gateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=account-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ACCOUNTSERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/accounts/**

spring.cloud.gateway.server.webflux.routes[2].id=transaction-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://TRANSACTIONSERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/transactions/**